//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduConnectApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIAOVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GIAOVIEN()
        {
            this.GIANGDAYs = new HashSet<GIANGDAY>();
            this.LOPs = new HashSet<LOP>();
            this.TO11 = new HashSet<TO1>();
        }
    
        public int MAGV { get; set; }
        public string HOTEN { get; set; }
        public string EMAIL { get; set; }
        public string SDT { get; set; }
        public string DIACHI { get; set; }
        public Nullable<System.DateTime> NTNS { get; set; }
        public Nullable<bool> GIOITINH { get; set; }
        public Nullable<int> MALOGIN { get; set; }
        public Nullable<int> MATO { get; set; }
        public Nullable<bool> DELETED { get; set; }
        public string AVA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIANGDAY> GIANGDAYs { get; set; }
        public virtual LOGIN LOGIN { get; set; }
        public virtual TO1 TO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOP> LOPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TO1> TO11 { get; set; }
    }
}
