//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduConnectApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOCSINH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOCSINH()
        {
            this.HOCTAPs = new HashSet<HOCTAP>();
            this.KETQUAs = new HashSet<KETQUA>();
            this.LOPs = new HashSet<LOP>();
            this.NHANXETs = new HashSet<NHANXET>();
            this.TBMONs = new HashSet<TBMON>();
            this.THANHTICHes = new HashSet<THANHTICH>();
            this.THIs = new HashSet<THI>();
        }
    
        public int MAHS { get; set; }
        public string HOTEN { get; set; }
        public Nullable<System.DateTime> NTNS { get; set; }
        public string NOISINH { get; set; }
        public Nullable<bool> GIOITINH { get; set; }
        public string DANTOC { get; set; }
        public string TONGIAO { get; set; }
        public string CHINHSACH { get; set; }
        public string SDT { get; set; }
        public string GHICHU { get; set; }
        public string SOHIEU { get; set; }
        public string DIACHI { get; set; }
        public string NIENKHOA { get; set; }
        public Nullable<int> MALOGIN { get; set; }
        public Nullable<bool> DELETED { get; set; }
    
        public virtual LOGIN LOGIN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOCTAP> HOCTAPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KETQUA> KETQUAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOP> LOPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NHANXET> NHANXETs { get; set; }
        public virtual PHUHUYNH PHUHUYNH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBMON> TBMONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THANHTICH> THANHTICHes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THI> THIs { get; set; }
    }
}
