//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduConnectApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHUHUYNH
    {
        public int MAHS { get; set; }
        public string HOTENBO { get; set; }
        public string HOTENME { get; set; }
        public string NGHEBO { get; set; }
        public string NGHEME { get; set; }
        public string SDTBO { get; set; }
        public string SDTME { get; set; }
        public Nullable<bool> DELETED { get; set; }
    
        public virtual HOCSINH HOCSINH { get; set; }
    }
}
